pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo 'Building...'
                sh 'npm install'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing...'
                sh 'npm run test:ci'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying...'
                // Your deployment steps
            }
        }
    }
}
