jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm ci

    - name: Set execute permissions for node_modules
      run: |
        sudo chmod -R 777 /home/runner/work/patient-appointment-scheduling/patient-appointment-scheduling/node_modules/

    - name: Run tests
      run: npm run test:ci
